### ISSUE TITLE
Can't work on iPad as cordova-app

### ISSUE THREAD

**Issue by akozenko** [bramstein/fontloader#4]
Hello. 
I have a problem with yours polyfill when run code as cordova app.

``` javascript
   function _loadSingleFontFace(fontName, url, options) {
      url = 'url("' + url + '")';
      var fontFace = new FontFace(fontName, url, options);
      return fontFace.load().then(function(loadedFace) {
         _doc.fonts.add(loadedFace);
         return loadedFace;
      });
   }
```

This code work fine as web-app on Safari, also its work fine as cordova-app on android. Could you help with this problem?

**Comment by bramstein** [comment]
Are there any errors or warnings?

**Comment by akozenko** [comment]
Yes. I have an error (see attach). In network-tab i see that font loaded.
![screen shot 2015-08-03 at 9 11 25 am](https://cloud.githubusercontent.com/assets/4434095/9031856/1e258514-39c1-11e5-9d7e-cc1ee55b5536.png)

**Comment by bramstein** [comment]
Hmm, interesting. Is there any way to set up a simple app to test this out? I think this is going to require more debugging.
