### ISSUE TITLE
Comparison with prior art

### ISSUE THREAD

**Issue by dandv** [bramstein/fontloader#5]
Hi @bramstein,

While looking for fontLoader event libraries, I found this one and also @smnh's [fontLoader](https://github.com/smnh/FontLoader), which had started development a few months earlier.

Since I assume you [looked around first](http://slides.com/dandv/prior-art) for an existing implementation before writing another library, I was wondering what the motivations were for coding anew.

**Comment by bramstein** [comment]
I'm not sure what you're asking. This fontloader project is a polyfill for the CSS font loading module, which has quite different goals. I'm aware of @smnh's font loading work, but it has some issues which made it unusable for me (though, I haven't checked recently if those issues are still there).

**Comment by dandv** [comment]
Just looking for a comparison with [alternatives](https://github.com/zachleat/fontfaceonload#alternatives) like @zachleat's.
