### ISSUE TITLE
Does this library implement document.fonts.ready()?

### ISSUE THREAD

**Issue by domhofmann** [bramstein/fontloader#6]
I'm using the minified `fontloader.js` and it seems like only `document.fonts.status` is available.

**Comment by bramstein** [comment]
Not yet. I'm confused by its implementation. It seems it will fire after all fonts in the document that are necessary to render the page are loaded. What happens to fonts that are loaded after that? It seems you won't get events from those. I'll add it once I figure out what exactly it is supposed to do (pull requests are welcome though!)
